import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import {
  JobCardComponent,
  JobCardData,
} from 'src/app/components/job-card/job-card.component'

@Component({
  selector: 'app-resume-page',
  standalone: true,
  imports: [CommonModule, JobCardComponent],
  templateUrl: './resume-page.component.html',
  styleUrls: ['./resume-page.component.scss'],
})
export class ResumePageComponent {
  jobs: JobCardData[] = [
    {
      title: 'Middle Fullstack Web Developer',
      employer: 'ASTEK Polska',
      employerUrl: 'https://astek.pl/',
      location: 'Remote, Poland',
      description: `My current job. It is an outsourcing company more on a corporate side of spectrum. For the whole at Astek I'm working on a single project in the field of healthcare. Here I've got the experience working with really big, even massive codebase with an extensive history of development and usage spanning well over a decade. Spring with Oracle SQL on backend and Angular with some inhouse libraries on the frontend. Collectively all the services I personaly have to work with contain million lines of code. Also, here I've got the experience working with a really big team in Scrum. I communicate with more than 20 people from my and other teams on a daily basis. Also, on this project I've got a pretty balanced portion of maintaining and developing some new functionalities`,
      startDate: new Date('2022-09-01'),
      responsibilities: [
        'New functionality development',
        'Project maintenance and support',
        'Regular code reviews',
        'Extensive code refactoring',
        'Extensive task estimation',
        'Database design',
        'Codebase documentation',
        'Team communication',
        'Testing',
        'Bug fixint',
        'Codebase analysis',
        'Codebase optimization',],
      technologies: [
        'Angular',
        'RxJS',
        'Git',
        'Oracle SQL',
        'Spring',
        'Java',
        'Jenkins',
        'TeamCity',
        'GitLab',
        'Jira',
        'Confluence',
        'MS Teams',
        'Python',
        'PL SQL',
        'Bash',
        'Linux',
        'Oracle VM VirtualBox',
      ]
    },
    {
      title: 'Frontend Web Developer',
      employer: 'MODSEN',
      employerUrl: 'https://www.modsen-software.com/',
      location: 'Remote, Belarus',
      description: `My first full-time job as a web developer. Here I've got more structure to my skills. Algorythms and data structures, design patterns, SOLID principles, etc. Also, here I've got the opportunity to focus on some specific technologies and not to pulverize my attention on everything at once. First experience on a big project, first experience with a big team, first experience with a outsourcing startup.`,
      responsibilities: [
        'New Functionality development (mainly Front-end)',
        'Project maintenance and support',
        'Code review',
        'Task estimation',
        'Databse design',
      ],
      startDate: new Date('2021-08-01'),
      endDate: new Date('2022-08-01'),
      technologies: [
        'HTML',
        'CSS',
        'Sass',
        'JavaScript',
        'TypeScript',
        'React',
        'Angular',
        'RxJS',
        'NgRx',
        'PostgreSQL',
        'Git',
        'TFVC',
        'MySQL',
        'Slack',
        'MS Teams',
        'TFS',
        'ASP.NET Core',
        'C#',
        'NestJS',
        'Express',
      ],
    },
    {
      title: 'Web Developer',
      employer: 'Freelance',
      location: 'Remote',
      description: `I've been working as a freelance web developer for more than a year. I've been woking with client from all over the world and I've been working on a wide range of projects on a wide range of positions. Anything from help with setting up a WordPress website to developing a custom web application from scratch.`,
      responsibilities: [
        'Web page layout and design',
        'Custom WordPress theme development',
        'Custom WordPress plugin development',
        'Custom Back-end development',
        'Tailored Web Application development and deployment',
        'Web Application maintenance and support',
        'Customer support',
        'Client communication',
      ],
      technologies: [
        'HTML',
        'CSS',
        'JavaScript',
        'TypeScript',
        'PHP',
        'WordPress',
        'React',
        'Redux',
        'C#',
        'Java',
        'SQL',
        'Jenkins',
      ],
      startDate: new Date('2020-02-01'),
      endDate: new Date('2021-07-1'),
    },
  ]
}
